spring:
    application:
        name: customer-service
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:25062/customer?createIfNotExists=true
        username: Admin
        password: TestPassword
        database: customer
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
server:
    port: 9002

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
