version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: product-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: alkhspamer
      MONGO_INITDB_ROOT_PASSWORD: TestPassword

