spring:
    application:
        name: discovery-service



eureka:
    client:
        registerWithEureka: false
        fetchRegistry: false
    instance:
        hostname: discovery
    server:
        waitTimeInMsWhenSyncEmpty: 0
server:
    port: 8761